spring:
  application:
    name: index
  datasource:
    #    type: com.alibaba.druid.pool.DruidDataSource
    #MySQL??
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/performante?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: password

mybatis:
  mapper-locations: classpath:mapper/*.xml